[fields]
article = ["Артикул", "Article", "SKU", "Item No", "Item Number"]
supplier = ["Поставщик", "Supplier", "Производитель", "Manufacturer"]
season = ["Сезон", "Season"]
name = ["Наименование", "Название", "Product Name", "Description of goods"]
sales_start = ["Старт продаж", "Начало продаж", "Sales Start"]
collection = ["Коллекция", "Collection"]
line = ["Линия", "Line"]
group = ["Группы", "группа", "Group"]
subgroup = ["Подгруппы", "подгруппа", "Subgroup"]
photo = ["Фото", "Photo", "Picture", "Image"]
description = ["Описание", "Description"]
model = ["Модель", "Model"]
size = ["Размер", "Size"]
manager = ["Ответственный менеджер", "Аналитик"]
quantity = ["Итого заказ", "Количество", "Quantity"]
retail_price = ["Предполагаемая цена", "Retail Price"]
purchase_price = ["Цена", "Цена, CNY", "Price", "Unit Price", "НОВЫЙ"]
currency = ["Валюта FOB", "Currency"]
moq = ["MOQ"]
target_price = ["TARGET PRICE"]
price_under_target = ["Цена под TARGET PRICE"]
comments = ["Комментарии", "Комментарий", "Comments"]
